apiVersion: v1
kind: Pod
metadata:
  name: app-php
  labels:
    name: app-php
spec:
  containers:
  - name: app
    image: viniciuspoa2/app-php:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
