apiVersion: batch/v1
kind: CronJob
metadata:
  name: job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
          restartPolicy: OnFailure
