apiVersion: v1
kind: Service
metadata:
  namespace: solutionsday
  name: solutionsdayblog-service
spec:
  type: ClusterIP
  selector:
    app: solutionsdayblog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
