version: "3.10"

services:
  db-menu-service:
    image: postgres:15
    networks:
      - "microservices"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=menu
      - POSTGRES_PASSWORD=dbmenu2023
      - POSTGRES_DB=menu
      - POSTGRES_HOST_AUTH_METHOD=trust
  menu-service:
    image: viniciuspoa2/menuservice
    networks:
      - "microservices"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=menu-service-db-menu-service-1
      - DATABASE_USERNAME=menu
      - DATABASE_PASSWORD=dbmenu2023
      - DATABASE_NAME=menu
    restart: always
networks:
  microservices:
    external: true